[2025-02-09T22:29:47.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T22:29:47.387+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mgp-airflow1.docker_command_hello manual__2025-02-09T22:29:44.986182+00:00 [queued]>
[2025-02-09T22:29:47.393+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mgp-airflow1.docker_command_hello manual__2025-02-09T22:29:44.986182+00:00 [queued]>
[2025-02-09T22:29:47.393+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-09T22:29:47.413+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): docker_command_hello> on 2025-02-09 22:29:44.986182+00:00
[2025-02-09T22:29:47.419+0000] {standard_task_runner.py:72} INFO - Started process 185 to run task
[2025-02-09T22:29:47.425+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'mgp-***1', 'docker_command_hello', 'manual__2025-02-09T22:29:44.986182+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/mgpMap.py', '--cfg-path', '/tmp/tmp4m5jb3wi']
[2025-02-09T22:29:47.428+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask docker_command_hello
[2025-02-09T22:29:47.444+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-09T22:29:47.480+0000] {task_command.py:467} INFO - Running <TaskInstance: mgp-airflow1.docker_command_hello manual__2025-02-09T22:29:44.986182+00:00 [running]> on host 8c9cea95fee4
[2025-02-09T22:29:47.562+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mgp-***1' AIRFLOW_CTX_TASK_ID='docker_command_hello' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T22:29:44.986182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-09T22:29:44.986182+00:00'
[2025-02-09T22:29:47.564+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T22:29:47.662+0000] {docker.py:367} INFO - Starting docker container from image python:3.9-slim
[2025-02-09T22:29:47.684+0000] {docker.py:375} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-09T22:29:48.421+0000] {docker.py:438} INFO - hello
[2025-02-09T22:29:49.227+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T22:29:49.229+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=mgp-***1, task_id=docker_command_hello, run_id=manual__2025-02-09T22:29:44.986182+00:00, execution_date=20250209T222944, start_date=20250209T222947, end_date=20250209T222949
[2025-02-09T22:29:49.284+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T22:29:49.301+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T22:29:49.302+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
